---
- name: suricata PPA install
  include: ppa-install.yml
  when: not suricata_install_from_sources

- name: suricata install from sources
  include: source-install.yml
  when: suricata_install_from_sources

- name: suricata configure
  include: configure.yml
  notify: start suricata